### ISSUE TITLE
Error loading script: freeu.py

### ISSUE THREAD

**Issue by mitsuke-code** [ljleb/sd-webui-freeu#31]
Error loading script: freeu.py
Traceback (most recent call last):
  File "D:\SDM\stable-diffusion-webui\modules\scripts.py", line 256, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\SDM\stable-diffusion-webui\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\SD\stable-diffusion-webui\extensions\sd-webui-freeu\scripts\freeu.py", line 291, in <module>
    script_callbacks.on_cfg_after_cfg(on_cfg_after_cfg)
AttributeError: module 'modules.script_callbacks' has no attribute 'on_cfg_after_cfg'

**Comment by ljleb** [comment]
A workaround is to update your webui to 1.6.0. I'll see if I can rely on the on_denoised callback instead.
